export const EMAIL_TEMPLATE_ID = {
  OTP: 'OTP',
  WELCOME: 'WELCOME',
  RESET_PASSWORD: 'RESET_PASSWORD',
  EMAIL_VERIFY: 'EMAIL_VERIFY',
  UPDATE_EMAIL_VERIFY: 'UPDATE_EMAIL_VERIFY',
  INVITATION_EMAIL: 'INVITATION_EMAIL',
  OTP_VERIFY: 'OTP_VERIFY',
  BOOKING_STATUS: 'BOOKING_STATUS',
  ACCOUNT_RECOVERY_REQUESTED: 'ACCOUNT_RECOVERY_REQUESTED',
  ACCOUNT_RECOVERY_COMPLETED: 'ACCOUNT_RECOVERY_COMPLETED',
  TWO_FACTOR_RESET: 'TWO_FACTOR_RESET',
  AGENCY_CLOSE_SCHEDULED: 'AGENCY_CLOSE_SCHEDULED',
  SUBSCRIPTION_NOTICE: 'SUBSCRIPTION_NOTICE',
} as const;

export const EMAIL_TEMPLATE_RUNTIME_ID: Record<EMAIL_TEMPLATE_ID, string> = {
  OTP: process.env.RESEND_TEMPLATE_OTP_ID!,
  WELCOME: process.env.RESEND_TEMPLATE_WELCOME_ID!,
  RESET_PASSWORD: process.env.RESEND_TEMPLATE_RESET_PASSWORD_ID!,
  EMAIL_VERIFY: process.env.RESEND_TEMPLATE_EMAIL_VERIFY_ID!,
  INVITATION_EMAIL: process.env.RESEND_TEMPLATE_TEAM_INVITE_ID!,
  UPDATE_EMAIL_VERIFY: process.env.RESEND_TEMPLATE_UPDATE_EMAIL_ID!,
  OTP_VERIFY: process.env.RESEND_TEMPLATE_VERIFY_EMAIL_OTP_ID!,
  // Réservation confirmée ou refusée (modèle à créer dans Resend)
  BOOKING_STATUS: process.env.RESEND_TEMPLATE_BOOKING_STATUS_ID!,
  // Modèles décrits dans src/modules/mail/templates/*.md (à créer dans Resend)
  ACCOUNT_RECOVERY_REQUESTED: process.env.RESEND_TEMPLATE_ACCOUNT_RECOVERY_REQUESTED_ID!,
  ACCOUNT_RECOVERY_COMPLETED: process.env.RESEND_TEMPLATE_ACCOUNT_RECOVERY_COMPLETED_ID!,
  TWO_FACTOR_RESET: process.env.RESEND_TEMPLATE_TWO_FACTOR_RESET_ID!,
  AGENCY_CLOSE_SCHEDULED: process.env.RESEND_TEMPLATE_AGENCY_CLOSE_SCHEDULED_ID!,
  // Avis d'abonnement (rappel, paiement, passage au Gratuit, downgrade) : un seul modèle générique
  SUBSCRIPTION_NOTICE: process.env.RESEND_TEMPLATE_SUBSCRIPTION_NOTICE_ID!,
};

export type EMAIL_TEMPLATE_ID = (typeof EMAIL_TEMPLATE_ID)[keyof typeof EMAIL_TEMPLATE_ID];
